FROM python:3.10
WORKDIR /bot
COPY ./requirements.txt /bot/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /bot/requirements.txt
COPY ./app /bot/app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
